### PR TITLE
Use Gradle

### PR DESCRIPTION
**Pull request by jamierocks**
Maven -> Gradle is like Ant -> Maven.

All you need to do is enter your maven-repo, follow [this](http://gradle.org/docs/current/userguide/maven_plugin.html).

### CODE REVIEW

**Comment by darkdiplomat** [comment]
What about shading the the dependencies into the build like we do with Maven?
What needs to be updated on Jenkins to continue the continuous integrations?
How does this even work?

**Comment by jamierocks** [comment]
Ah, stupid me forgot to shade the dependencies in :|
It's pretty simple [eg](https://gist.github.com/jamierocks/88d2d841a460f4efe88f).
You can see another example [here](https://github.com/SpongePowered/Sponge/blob/master/build.gradle#L93).

I am not familiar with Jenkins, but once you have your repo settings sorted, you probably just need to run 'gradle build uploadArchives'.

Gradle has a very extensive user guide, you can find [here](http://gradle.org/docs/current/userguide/userguide.html).

**Comment by jamierocks** [comment]
Ver simply, to get your repo working (assuming it uses ssh), you just need to make a gradle.properties file (+ gitignore it) and enter in the repo, the repoUserName and repoPassword.
eg:
    repo: http://repo.visualillusionsent.net/repository/public/
    repoUserName: Duck
    repoPassword: DuckGo

**Comment by toddharrison** [comment]
Is there a reason to switch besides it just being the "new" thing?

**Comment by jamierocks** [comment]
If CanaryMod ever uses MCP mappings, ForgeGradle or VanillaGradle is incredibly useful.

**Comment by Larry1123** [comment]
@jamierocks we could use MCP mappings without gradle. It is just that we truly have not tried to.

**Comment by jamierocks** [comment]
Yes - you could make a system half as powerful as forge gradle, and delight every dev that works on canarymod.
Not only is gradle more powerful than maven is has an already established set of plugins for working with minecraft.
    _____________________________

**Comment by jamierocks** [comment]
@darkdiplomat I will get some images done, showing the setup using Jenkins. It's nice that Jenkins has Gradle support, although it really doesn't make it any easier... unless you don't like using wrappers.

**Comment by 14mRh4X0r** [comment]
Gradle is cool, just saying.

**Comment by jamierocks** [comment]
It sure is :P

**Comment by jamierocks** [comment]
#233.

**Pull request closed without merging**
